personalwebsite/games/urls.py
from django.urls import path

from . import views

app_name = 'games'

urlpatterns = [
    path('<pk>/', views.GameDetail.as_view(), name='game_detail'),
]

personalwebsite/personalwebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(settings.CONFIG['ADMIN_URL']+'/', admin.site.urls),
    path('', include('portfolio.urls', namespace='portfolio')),
    path('games/', include('games.urls', namespace='games')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personalwebsite/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contact/', views.ContactMe.as_view(), name='contact'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    path('projects/<pk>/', views.ProjectDetail.as_view(), name='project_detail'),
]

personalwebsite/games/models.py
import os

from django.db import models


class Game(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def get_upload_path(instance, filename):
        return os.path.join(
            'games',
            instance.title,
            filename
        )

    data = models.FileField(upload_to=get_upload_path)
    framework = models.FileField(upload_to=get_upload_path)
    loader = models.FileField(upload_to=get_upload_path)
    wasm = models.FileField(upload_to=get_upload_path)

    def __str__(self):
        return self.title

personalwebsite/portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=255, help_text="Enter a project name.")
    subtitle = models.CharField(max_length=255, null=True, blank=True, help_text="Enter a brief description of the project.")
    description = models.TextField(null=True, blank=True, help_text="Enter a detailed description of the project.")
    image = models.ImageField(upload_to='portfolio/projects', null=True, blank=True, help_text="Upload an image for the project.")

    def __str__(self):
        return self.title


class Link(models.Model):
    text = models.CharField(max_length=255)
    url = models.URLField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='links')

    def __str__(self):
        return self.project.title + ' | ' + self.text


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    contact_time = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name + ' | ' + self.subject


class Spam(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    website = models.CharField(max_length=255)
    contact_time = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name + ' | ' + self.subject

personalwebsite/portfolio/forms.py
from datetime import datetime

from django import forms
from django.core.mail import send_mail

from .models import Contact, Spam


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Name'}),
    )
    email = forms.EmailField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Email'}),
    )
    subject = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Subject'}),
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Message', 'style': 'height: 10em;'}),
    )
    website = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'style': 'display: none;'}),
    )

    def honeypot_empty(self):
        return len(self.cleaned_data['website']) == 0

    def save_contact(self, ip, user_agent):
        contact = Contact(
            name=self.cleaned_data['name'],
            email=self.cleaned_data['email'],
            subject=self.cleaned_data['subject'],
            message=self.cleaned_data['message'],
            ip_address=ip,
            user_agent=user_agent,
        )
        contact.save()

    def save_spam(self, ip, user_agent):
        spam = Spam(
            name=self.cleaned_data['name'],
            email=self.cleaned_data['email'],
            subject=self.cleaned_data['subject'],
            message=self.cleaned_data['message'],
            website=self.cleaned_data['website'],
            ip_address=ip,
            user_agent=user_agent,
        )
        spam.save()

    def send_email(self):
        message = 'Name: ' + self.cleaned_data['name'] + \
            '\nEmail: ' + self.cleaned_data['email'] + \
            '\nSubject: ' + self.cleaned_data['subject'] + \
            '\n\n' + self.cleaned_data['message']

        send_mail(
            'Personal Website Contact: ' + self.cleaned_data['subject'],
            message,
            'lee@leemccarthy.com',
            ['lee@leemccarthy.com'],
        )

personalwebsite/games/views.py
from django.views.generic import DetailView

from .models import Game


class GameDetail(DetailView):
    template_name = 'games/game_detail.html'
    model = Game

personalwebsite/portfolio/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, TemplateView

from .forms import ContactForm
from .models import Project


class Index(FormView):
    template_name = 'portfolio/index.html'
    form_class = ContactForm
    success_url = reverse_lazy('portfolio:thankyou')

    def form_valid(self, form):
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        user_agent = self.request.META.get('HTTP_USER_AGENT')
        if form.honeypot_empty():
            form.save_contact(ip, user_agent)
            form.send_email()
        else:
            form.save_spam(ip, user_agent)
        self.request.session['contact_name'] = form.cleaned_data['name']
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.order_by('-pk')
        return context


class ContactMe(FormView):
    template_name = 'portfolio/contact_me.html'
    form_class = ContactForm
    success_url = reverse_lazy('portfolio:thankyou')

    def form_valid(self, form):
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        user_agent = self.request.META.get('HTTP_USER_AGENT')
        if form.honeypot_empty():
            form.save_contact(ip, user_agent)
            form.send_email()
        else:
            form.save_spam(ip, user_agent)
        self.request.session['contact_name'] = form.cleaned_data['name']
        return super().form_valid(form)


class ThankYou(TemplateView):
    template_name = 'portfolio/contact_thank_you.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = self.request.session.pop('contact_name', None)
        return context


class ProjectDetail(DetailView):
    template_name = 'portfolio/project_detail.html'
    model = Project

personalwebsite/games/templates/games/game_detail.html
{% extends 'base.html' %}
{% load static %}
{% block unique_head %}
  <!-- <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> -->
  <title>{{ game.title }} | Lee McCarthy</title>
{% endblock %}
{% block content %}
<h1 class="mt-3" style="text-align: center;">{{ game.title }}</h1>
<div class="mt-3" style="text-align: center;">
  <canvas id="unity-canvas" style="width: 960px; height: 600px; background: #231F20;"></canvas>
  <script src="{{ game.loader.url }}"></script>
  <script>
    createUnityInstance(document.querySelector("#unity-canvas"), {
      dataUrl: "{{ game.data.url }}",
      frameworkUrl: "{{ game.framework.url }}",
      codeUrl: "{{ game.wasm.url }}",
      streamingAssetsUrl: "StreamingAssets",
      companyName: "Lee McCarthy",
      productName: "{{ game.title }}",
      productVersion: "1.0",
    });
  </script>
</div>
{% endblock %}

personalwebsite/portfolio/templates/portfolio/contact_me.html
{% extends 'base.html' %}
{% load portfolio_tags %}
{% block unique_head %}<title>Contact Me | Lee McCarthy</title>{% endblock %}
{% block content %}
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col text-center">
      <h1>Contact Me</h1>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-lg-6">
      <form method="POST" onsubmit="disableSubmit(this)">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="row">
          <div class="col-6">
            <div class="form-floating mb-3">
              {% if form.name.errors %}
              {{ form.name|addclass:"form-control is-invalid" }}
              {% else %}
              {{ form.name|addclass:"form-control" }}
              {% endif %}
              <label for="id_{{ form.name.label.lower }}">{{ form.name.label }}</label>
              <div id="id_{{ form.name.label.lower }}Feedback" class="invalid-feedback">
                {{ form.name.errors.as_text }}
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="form-floating mb-3">
              {% if form.email.errors %}
              {{ form.email|addclass:"form-control is-invalid" }}
              {% else %}
              {{ form.email|addclass:"form-control" }}
              {% endif %}
              <label for="id_{{ form.email.label.lower }}">{{ form.email.label }}</label>
              <div id="id_{{ form.email.label.lower }}Feedback" class="invalid-feedback">
                {{ form.email.errors.as_text }}
              </div>
            </div>
          </div>
        </div>
        <div class="form-floating mb-3">
          {% if form.subject.errors %}
          {{ form.subject|addclass:"form-control is-invalid" }}
          {% else %}
          {{ form.subject|addclass:"form-control" }}
          {% endif %}
          <label for="id_{{ form.subject.label.lower }}">{{ form.subject.label }}</label>
          <div id="id_{{ form.subject.label.lower }}Feedback" class="invalid-feedback">
            {{ form.subject.errors.as_text }}
          </div>
        </div>
        <div class="form-floating mb-3">
          {% if form.message.errors %}
          {{ form.message|addclass:"form-control is-invalid" }}
          {% else %}
          {{ form.message|addclass:"form-control" }}
          {% endif %}
          <label for="id_{{ form.message.label.lower }}">{{ form.message.label }}</label>
          <div id="id_{{ form.message.label.lower }}Feedback" class="invalid-feedback">
            {{ form.message.errors.as_text }}
          </div>
        </div>
        {{ form.website }}
        <div class="text-center">
          <input class="btn btn-primary" type="submit" name="submit_btn" value="Submit">
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

personalwebsite/portfolio/templates/portfolio/contact_thank_you.html
{% extends 'base.html' %}
{% block unique_head %}<title>Thank You | Lee McCarthy</title>{% endblock %}
{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col text-center">
      <h1>Thank you for getting in contact{% if name %}, {{ name }}{% endif %}!</h1>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col text-center">
      <a class="btn btn-primary" href="{% url 'portfolio:index' %}">Return to Home</a>
    </div>
  </div>
</div>
{% endblock %}

personalwebsite/portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}
{% load portfolio_tags %}
{% block unique_head %}<title>Index | Lee McCarthy</title>{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8 text-center mt-3">
      <img src="{% static 'portfolio/images/me.jpg' %}" alt="A picture of me" class="img-fluid">
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row mt-3">
    <div class="col text-center">
      <h1>Projects</h1>
    </div>
  </div>
  <div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-12 mt-3">
      <div class="card h-100">
        <div class="ratio ratio-4x3">
          {% if project.image %}
          <img src="{{ project.image.url }}" alt="{{ project.title }} image" class="card-img-top" style="object-fit: cover;">
          {% else %}
          <img src="{% static 'portfolio/images/Blank.png' %}" alt="blank image" class="card-img-top" style="object-fit: cover;">
          {% endif %}
        </div>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title">{{ project.title }}</h5>
          {% if project.subtitle %}
          <p class="card-text">{{ project.subtitle }}</p>
          {% endif %}
          <a href="{% url 'portfolio:project_detail' project.pk %}" class="btn btn-primary mt-auto">View</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<hr>
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col text-center">
      <h1>Contact Me</h1>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-lg-6">
      <form method="POST" onsubmit="disableSubmit(this)">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="row">
          <div class="col-6">
            <div class="form-floating mb-3">
              {% if form.name.errors %}
              {{ form.name|addclass:"form-control is-invalid" }}
              {% else %}
              {{ form.name|addclass:"form-control" }}
              {% endif %}
              <label for="id_{{ form.name.label.lower }}">{{ form.name.label }}</label>
              <div id="id_{{ form.name.label.lower }}Feedback" class="invalid-feedback">
                {{ form.name.errors.as_text }}
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="form-floating mb-3">
              {% if form.email.errors %}
              {{ form.email|addclass:"form-control is-invalid" }}
              {% else %}
              {{ form.email|addclass:"form-control" }}
              {% endif %}
              <label for="id_{{ form.email.label.lower }}">{{ form.email.label }}</label>
              <div id="id_{{ form.email.label.lower }}Feedback" class="invalid-feedback">
                {{ form.email.errors.as_text }}
              </div>
            </div>
          </div>
        </div>
        <div class="form-floating mb-3">
          {% if form.subject.errors %}
          {{ form.subject|addclass:"form-control is-invalid" }}
          {% else %}
          {{ form.subject|addclass:"form-control" }}
          {% endif %}
          <label for="id_{{ form.subject.label.lower }}">{{ form.subject.label }}</label>
          <div id="id_{{ form.subject.label.lower }}Feedback" class="invalid-feedback">
            {{ form.subject.errors.as_text }}
          </div>
        </div>
        <div class="form-floating mb-3">
          {% if form.message.errors %}
          {{ form.message|addclass:"form-control is-invalid" }}
          {% else %}
          {{ form.message|addclass:"form-control" }}
          {% endif %}
          <label for="id_{{ form.message.label.lower }}">{{ form.message.label }}</label>
          <div id="id_{{ form.message.label.lower }}Feedback" class="invalid-feedback">
            {{ form.message.errors.as_text }}
          </div>
        </div>
        {{ form.website }}
        <div class="text-center">
          <input class="btn btn-primary" type="submit" name="submit_btn" value="Submit">
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

personalwebsite/portfolio/templates/portfolio/project_detail.html
{% extends 'base.html' %}
{% block unique_head %}<title>{{ project.title }} | Lee McCarthy</title>{% endblock %}
{% block content %}
<div class="container">
  <div class="row mt-3">
    <div class="col text-center">
      <h1>{{ project.title }}</h1>
      {% if project.subtitle %}
      <h5>{{ project.subtitle }}</h5>
      {% endif %}
      {% if project.image %}
      <img src="{{ project.image.url }}" alt="project image" class="mt-3 mb-3" style="width: 80%;">
      {% endif %}
      <p>{{ project.description }}</p>
      {% for link in project.links.all %}
      <div class="mt-3">
        <a href="{{ link.url }}" class="btn btn-primary">{{ link.text }}</a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

personalwebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block unique_head %}<title>Lee McCarthy</title>{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script>
      function disableSubmit(form) {
        form.submit_btn.disabled = true;
        form.submit_btn.value = 'Please wait...';
      }
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'portfolio:index' %}">Lee McCarthy</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/lee-mccarthy">GitHub</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <div class="container mt-5"></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>